version: "3.9"
services:
  DB:
    container_name: GruppA-DB
    image: mysql:latest
    environment: 
      - MYSQL_USER=${SPRING_DATASOURCE_USER}
      - MYSQL_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - MYSQL_DATABASE=${SQL_SERVER_NAME}
    restart: always
    ports:
      - "3306:3306"
  keycloak_client:
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
     - KEYCLOAK_ADMIN=${KEYCLOACK_ADMIN_NAME}
     - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOACK_ADMIN_PASSWORD}
    command: start-dev
    volumes: 
      -  ./keycloak/realms:/opt/keycloak/data/import
    ports:
      - "8000:8080"
